### ISSUE TITLE
sudo: command not found

### ISSUE THREAD

**Issue by jwoertink** [cloudamqp/lavinmq-action#3]
I'm using this in a new shard. I just want to make sure that I've set it up correctly. I got a few command not found errors in the CI though

https://github.com/cable-cr/cable-amqp/blob/085eca9555cbe44ae2ba0975b12970e8c6ec7a2b/.github/workflows/ci.yml#L36-L37

![image](https://github.com/cloudamqp/lavinmq-action/assets/2391/d309a074-5e85-4b34-9814-57b3ddc13ce4)

**Comment by carlhoerberg** [comment]
It's because you're in a container (`container: crystallang/crystal:${{ matrix.crystal_version }}`). You should start a service with lavinmq instead, that your container then reaches out to: https://docs.github.com/en/actions/using-containerized-services/about-service-containers

**Comment by carlhoerberg** [comment]
```yaml
jobs:
  runner:
    ... your normal stuff
    services:
      lavinmq:
        image: cloudamqp/lavinmq
        ports:
          - 5672:5672
          - 15672:15672
```
